### ISSUE TITLE
Can't select (highlight) text on last line

### ISSUE THREAD

**Issue by shem86** [yairEO/fakescroll#1]
The absolute positioned .scrollWrap::after blocks mouse selection,
You can reproduce in the Demo page: http://yaireo.github.io/fakescroll/
Just try to select the last line of text.

**Comment by yairEO** [comment]
it has nothing to do with the plugin. 
ignore the content, it's just a dummy text with some nice CSS for the demo page.

**Comment by shem86** [comment]
Oh I see now, I thought it was part of the plugin css.
Thanks.
