### ISSUE TITLE
Give the .fakeScroll__track div a class when there is nothing to scroll

### ISSUE THREAD

**Issue by ataylor32** [yairEO/fakescroll#17]
When no scrolling is necessary, the `.fakeScroll__bar` div is hidden with `display: none`. This is good, but I think it would also be good if the `.fakeScroll__track` div was given a class like `.fakeScroll__has_hidden_bar` or something along those lines so that developers could more easily update the styling of the track when there is nothing to scroll.

**Comment by yairEO** [comment]
Good idea, thanks!

**Comment by ataylor32** [comment]
Do you know when this might be added? Is there anything I can do to help?

**Comment by yairEO** [comment]
Hi I am spending all day to port my code to React and once it's done I'll release it along with the change you've requested (hopefully today but I'm currently facing one last tough bug with the React port)

**Comment by yairEO** [comment]
Done. update to `v2.2.0`, see [docs](https://github.com/yairEO/fakescroll#the-above-markup-will-now-become) for DOM structure.

**Comment by ataylor32** [comment]
Thanks! In order to get this working properly on my project, I had to remove the following from `onScrollResize`:

```javascript
this.DOM.scope.classList.toggle('fakeScroll--hasBar', this.state.scrollRatio < 1)
```

I then added the following to `moveBar` at the same point where `this.DOM.bar.style.cssText` gets set:

```javascript
if (scrollHeight <= ownHeight) {
    this.DOM.scope.classList.remove('fakeScroll--hasBar');
}
else {
    this.DOM.scope.classList.add('fakeScroll--hasBar');
}
```

**Comment by yairEO** [comment]
Why did you remove it? `moveBar` is not the place for it and you should not change the source code or you'll be out-of-sync with future updates...

**Comment by ataylor32** [comment]
You can look at #18 for context. I couldn't get that to work correctly without the change I mentioned in my previous comment. `moveBar` seemed like an appropriate place for it because that's where the `.fakeScroll__bar` div gets `display: none` added or removed.
