### ISSUE TITLE
Improve bar usability

### ISSUE THREAD

**Issue by ataylor32** [yairEO/fakescroll#19]
There are a couple of usability issues with the bar:

1. With a native scrollbar, clicking in the track below the bar will cause the content to scroll down. With fakescroll, clicking in the track below the bar doesn't do anything.
1. You can't interact with the bar on touch devices

**Comment by yairEO** [comment]
1. yes you can click on the track to scroll the content
2. yes it does work on mobile

Made sure of both of those 6 years ago when I wrote this code.
it's works on the [demo page](https://yaireo.github.io/fakescroll/) of this code. (see the second example for clicking anywhere on the track to scroll there)

**Comment by yairEO** [comment]
![Uploading image.png…]()

**Comment by yairEO** [comment]
![image](https://user-images.githubusercontent.com/845031/94312630-883e4a80-ff7d-11ea-9164-351c9ca5f2e6.png)
