### ISSUE TITLE
Scrollbar moves away from pointer

### ISSUE THREAD

**Issue by csakip** [yairEO/fakescroll#2]
It is quite annoying that when the scrollbar is hiding and you move the cursor on it, it moves to it's active position but that's not under the cursor anymore. Basically it avoids the pointer.
Apart from this, it's a great script.

**Comment by yairEO** [comment]
this is nothing to do with the script. it's a CSS thing. You are referring to the specific demo I guess, which is only a demo page after all, and you can style it however you see fit.

**Comment by csakip** [comment]
Thanks. :)
Well, it did stopped me from downloading and trying it myself, so it might be worth to change that on the demo page.

**Comment by yairEO** [comment]
you said the CSS issue had stopped from downloading (and possibly using) this script. This implies you are in need of a custom scrollbar script. I know of non better alternatives than this one, and that was the reason I wrote it. if you were not content with it, and used found a better one, please state its benefits so I would know what sort of demands some developers expect from such a script. I care deeply about performance, filesize & flexibility.

**Comment by csakip** [comment]
I check jqueryrain daily and collect the scripts that I think will be useful in the future. I usually check the demo and if it's good, I save the link. So I checked your demo and found that annoying bug and didn't save the link because of that. But it happened that I had some free time and thought, I will report the issue so the developer would know about that bug.
