### ISSUE TITLE
any cdn to use? 

### ISSUE THREAD

**Issue by Duplore** [yairEO/fakescroll#23]
is there a cdn?

**Comment by yairEO** [comment]
Almost all open-source libs automatically gets scanned by CDN providers. 

I will now choose a random CDN, search there, and answer you:
https://www.jsdelivr.com/package/npm/@yaireo/fakescroll

**Comment by Duplore** [comment]
@yairEO how do i even get this to work iv'e followed what was said but to nothing working

**Comment by yairEO** [comment]
Click these two files:

![image](https://user-images.githubusercontent.com/845031/206565773-9f4254df-bfb3-4b6d-9afd-1e414dfff3dd.png)

Copy the urls, and include them in your HTML, as `script` and `stylesheet`. Google that ("how to include X in an HTML page)
