### ISSUE TITLE
Scroll event

### ISSUE THREAD

**Issue by loeffe1** [yairEO/fakescroll#24]
Is there no event to allow scrolling or setting scrollRatio?

**Comment by yairEO** [comment]
What do you mean?
"event to allow scrolling"?

*fakescroll* is only visually changes the scrollbar by replacing it with a fake one.
it does not affect the scroll in any way. the real scrollbar is just hidden.

**Comment by loeffe1** [comment]
This will scroll to the bottom of .my-div but will do nothing on the same element if fakescroll has been initialized on it

```
$('.my-div').animate({
    scrollTop: $('.my-div')[0].scrollHeight - $('.my-div')[0].clientHeight
}, 1000);
```

**Comment by loeffe1** [comment]
I just realized I need to animate .fakeScroll__content

**Comment by yairEO** [comment]
Your code snippet is ancient. This is how things used to work 10+ years ago.

Use this to animate a scroll to the bottom:


```js
$('.my-div')[0].scroll({
  top: 9999,
  behavior: 'smooth'
});
```
https://developer.mozilla.org/en-US/docs/Web/API/Element/scroll

https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior
