### ISSUE TITLE
Remove jQuery dependency

### ISSUE THREAD

**Issue by buzinas** [yairEO/fakescroll#5]
Since jQuery is becoming deprecated, I think it's time to make this a standalone library instead of a jQuery plugin. Any chances of doing that?

**Comment by yairEO** [comment]
jquery is not becoming deprecated. That is just total misinformation being fed to developers on certain media channels. I have data showing jQuery usage is growing cross-web. jQuery is absolutely amazing, been using it for 10 years and I see no reason to stop, unless using native DOM would be easier, which isn't the case. try to convert it to non-jQuery and you will quickly see the difficulties. almost all my open-source project are jQuery-based..

**Comment by buzinas** [comment]
Already did that:
http://github.com/buzinas/simple-scrollbar

It works on IE9+, FF, Chrome, Opera, and Chrome mobile/Android browser.
Didn't have time to test on Safari, though, but it's probably working.

It was pretty simple to make the changes, in fact.

---

About being deprecated, obviously it was an overstatement. But as soon as
ES5 became more stable and ES6 will be a breaking change, jQuery is a heavy
library that - in my humble opinion - shouldn't be a dependency for many of
those simple libtaries.

Thanks for your fast response and for your great library too, it was an
amazing point of start for me.
Em 06/08/2015 11:18, "vsync" <notifications@github.com> escreveu:

**Comment by yairEO** [comment]
what is the benefit in making the code ES6? it's not like it's  faster or much less code, and probably 99% of developers won't be able to understand it

**Comment by buzinas** [comment]
Well, since it will be native in a few months and it will be easier to use
as a module, I thought it would be good to have both versions.

But there is the vanilla Javascript version too :)

People who develops for the newest frameworks like Aurelia and Angular2.0
are already developing with ES6 by default and that other version will fit
for them.

But you can use any version you want. In the demo page, I use the standard
vanilla Javascript (simple-scrollbar. js).
Em 06/08/2015 12:45, "vsync" <notifications@github.com> escreveu:

**Comment by yairEO** [comment]
Why did you renamed it, and also, why didn't you mention the code was ported from mine? 
That's not very nice..

**Comment by buzinas** [comment]
I've renamed it because I didn't like the current name, and the classes etc.

About not mentioning, that was my fault, but I'll do that.

Didn't yet because I preferred to test it better before anything else.

**Comment by yairEO** [comment]
@buzinas - you have removed my credits I see. This is **not** cool bro. it's my software and you're publishing it as yours..

**Comment by buzinas** [comment]
I have removed it, because it's not only a vanilla javascript version of yours anymore, but I have included again in a different way. Won't remove it anymore, didn't know you actually care about that, sorry.

**Comment by yairEO** [comment]
Yes I care a lot, I worked hard to come with the smart way of doing what I did here, there wasn't one single thing on the whole internet which was as good as this method, and imagine someone just cloned my idea, changed here and there and removed the credits... the core idea is what I care about, the actual code is not important..code is a matter of skill but to come up with ideas is what it's all about :)
