### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by littleguga** [yairEO/fakescroll#9]
Win7, last Chrome

https://jsbin.com/qupexihuri/1/edit?html,css,js,output

Only demo: https://jsbin.com/qupexihuri/1/

**Comment by littleguga** [comment]
I really don't understand what's going wrong.

**Comment by yairEO** [comment]
what is supposed to happen? I don't understand the demo page

**Comment by littleguga** [comment]
@yairEO rewrote demo: https://jsbin.com/zedogisuli

There is a ".big" block with green background in ".orange" block. I want to make ".orange" block scrollable with fakeScroll plugin.

**Comment by yairEO** [comment]
Here you go - https://jsbin.com/berema/1/edit?html,css,js,output

changed the CSS and the javascript as well. not sure
